FROM silex/emacs:25.1-dev

RUN apt update \
    && apt install -y python3 \
    && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /work
ENV PATH /cask/bin:$PATH

CMD ["bash"]
