FROM silex/emacs:25.2-dev

RUN apt update \
    && apt install -y python3 \
    && rm -rf /var/lib/apt/lists/*

RUN ln -sf /usr/bin/python3 /usr/bin/python

WORKDIR /cask
ENV PATH /cask/bin:$PATH

CMD ["bash"]
