FROM silex/emacs:{{version}}-dev

RUN apt update \
    && apt install -y python3 \
    && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /cask
ENV PATH /cask/bin:$PATH

CMD ["bash"]
