(source 'melpa)

(depends-on "carton")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "expand-region")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "popwin")
(depends-on "projectile")
(depends-on "s")
(depends-on "smex")
(depends-on "wrap-region")
(depends-on "yasnippet")
